### ISSUE TITLE
求作者联系方式

### ISSUE THREAD

**Issue by luduangit** [xiandyun/PhoneCall#5]
作者能留下一个联系方式吗，最近在做一个类似的APP，我有些问题想要咨询一下，或者加我的QQ：342599832，谢谢！

**Comment by LostStarTvT** [comment]
有问题可以在这问下

**Comment by luduangit** [comment]
是这样的，我打算在聊天界面加个打语音电话的按钮，按下就可以进行语音电话，所以我去掉了输入IP地址点击拨打的界面，直接由聊天界面用intent将IP地址传递到VoIP的activity中，并在VoIP的activity的onCreate方法进行给provider.setTargetIP(targetIP);由于你写的代码是在onclick方法进行给provider给他的IP值，我将这一步放在voipactivity的onCreate方法中就会出现provider是空的情况，set值就会报错，求教一下怎么个情况，由于是第一次做安卓，经验不够，还望您能够给我解答一下，谢谢。

**Comment by LostStarTvT** [comment]
> 是这样的，我打算在聊天界面加个打语音电话的按钮，按下就可以进行语音电话，所以我去掉了输入IP地址点击拨打的界面，直接由聊天界面用intent将IP地址传递到VoIP的activity中，并在VoIP的activity的onCreate方法进行给provider.setTargetIP(targetIP);由于你写的代码是在onclick方法进行给provider给他的IP值，我将这一步放在voipactivity的onCreate方法中就会出现provider是空的情况，set值就会报错，求教一下怎么个情况，由于是第一次做安卓，经验不够，还望您能够给我解答一下，谢谢。

你要调用
```java
 public static ApiProvider getProvider() {
        if (provider == null) {
            provider = new ApiProvider();
        }
        return provider;
    }
```
这个单例方法获取到provider对象。

**Comment by luduangit** [comment]
上次的问题解决了，作者能加个联系方式吗，我给你发了邮件不知道你看见了吗，能不能给我指导一下，有一些问题实在是不懂，正在做毕设没多少时间了，还望作者能帮帮我，十分感谢。

**Comment by luduangit** [comment]
就是我把电话功能加在我现有的功能上，点击按钮进行通话，为什么呼叫的对象没有唤起接电话的页面呢
